### ISSUE TITLE
Cuda and OpenCL Hashing

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#13]
Add support for Cuda and OpenCL sha256 string hashing to increase performance.

https://github.com/NVIDIA/libcudacxx

```bash
sudo apt install ocl-icd-opencl-dev
```

Additional tooling can be added in the `CMakeLists.txt` file.

**Comment by c3rb3ru5d3d53c** [comment]
jbx and I discussed we want to do tlsh, sha256 and entropy offloaded to GPU but through a new library called `blcuda`.

**Comment by jbx81-1337** [comment]
- [x] sha256
- [ ] entropy 
- [ ] tlsh
