### ISSUE TITLE
CMakeLists.txt - Change ExternalProject_Add to findpackage

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#130]
**Is your feature request related to a problem? Please describe.**
As mentioned in #127, we should move to using `findpackage` instead as `ExternalProject_Add` introduces issues with `Windows` builds.

**Describe the solution you'd like**
The solution would be to add git submodules for `LIEF`, `tlsh`, and `capstone` and use `findpackage` instead.

**Describe alternatives you've considered**
N/A

**Additional context**
This was suggested by @mrexodia :smile:

**Comment by c3rb3ru5d3d53c** [comment]
So `find_package` does not appear to be what we would want for git submodules, we would want `add_subdirectory`

**Comment by c3rb3ru5d3d53c** [comment]
The downside is that with git submodules it is difficult for us to version control those dependencies unless we use git in cli later to checkout a specific version. I think for repos in which we have control over to help with windows builds we can do forks and still use `ExternalProject_Add` much like we are doing already.

**Comment by mrexodia** [comment]
My idea would be something like this: Make a subdirectory `deps` that has all the `ExternalProject_Add` calls and builds the third party dependencies.

Then in the main project you create `Find<module>.cmake` which creates an `IMPORTED` library pointing to LIEF for example. Then the build process looks like this:
- `cmake -B deps/build -S deps && cmake --build deps/build` <- this will pull and build the dependencies
- `cmake -B build -DDEPS_BUILD_FOLDER:FILEPATH=deps/build`

Then in the main project's `CMakeLists.txt`:

```cmake
list(PREPEND CMAKE_MODULE_PATH "cmake")
find_package(LIEF REQUIRED)
```

This would then get you `IMPORTED` targets that point to `${DEPS_BUILD_FOLDER}/install/lief` (etc). The advantage of this system is that you only build the dependencies once and you keep your main project clean. Also on CI you can easily do caching of the dependencies etc.

The downside of course is that you end up having to do a lot of work to properly wrap the dependencies. Basically you are recreating vcpkg on a small scale.
