### ISSUE TITLE
Granularity of the output

### ISSUE THREAD

**Issue by nofiv** [c3rb3ru5d3d53c/binlex#19]
Hello, nice project!. I'm wondering whether it wouldn't be useful to make the output more granular - additionally generate traits/bytes for individual blocks/instructions/opcodes/operands. I believe that it would be useful for subsequent processing in some cases, e.g. [the first team](https://youtu.be/VLQTRlLGz5Y?t=441) in the Microsoft Malware Classification Challenge used frequency of opcodes and their N-grams among other things.

**Comment by c3rb3ru5d3d53c** [comment]
So we do individual blocks as traits, that part we are already doing.

It would also be possible to output trait type of single instructions with wildcards, which would provide more granular output.

This would give us trait types of `block`, `function` and `instruction`

**Comment by c3rb3ru5d3d53c** [comment]
However, operands like memory operands and immutables are hardly useful for classifying malware in my experience.

I can certainly look at meeting in the middle and doing wildcarded single instruction traits though :)

**Comment by nofiv** [comment]
I thought that the operands could be useful in some cases too when they contain some unique values such as hard-coded keys, hexadecimal IPs or crypto constants. Anyway, thank you for the clarification and adding the instruction trait!

**Comment by c3rb3ru5d3d53c** [comment]
@nofiv that is correct there are "some" cases where there are unique hard-coded values from the compiler.

Hexadecimal IPs typically are changed at compile time for many different families of malware which would cause unreliable results.

Crypto constants are typically found in goodware as well, which would potentially cause false positives.

But yes, I can certainly meet in the middle with an instruction trait.

**Comment by c3rb3ru5d3d53c** [comment]
Hmm doing some initial testing with this and it would mean we would have to lock the mutex in the threaded decompiler every instruction, the side-effect of this is very poor performance :disappointed:

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/147028960-54264146-1d39-4e64-992f-50b84f4c45db.png)

It's running but it's suuuper slow :/

**Comment by c3rb3ru5d3d53c** [comment]
Eh was a mutex issue, but here it is!

![image](https://user-images.githubusercontent.com/79795199/147030796-7996be39-fb4f-4ec6-aee5-9874d4542c13.png)

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/147098059-bd406276-b440-4f39-8715-1f83076e9a22.png)
