### ISSUE TITLE
Problems with instructions

### ISSUE THREAD

**Issue by nofiv** [c3rb3ru5d3d53c/binlex#25]
The latest version of binlex v1.1.1 outputs some seemingly incorrect instruction traits. Tested on an OpenSSL [library](https://curl.se/windows/dl-7.77.0_1/openssl-1.1.1k_1-win64-mingw.zip) (SHA1:ef406228f7694359c5f87e2ee7b4f760dcf160f6). Command `binlex -m pe:x86_64 --instructions -i <lib_name> | jq -r 'select(.type == ("instruction")) | .trait'` returns a number of weird traits such as 00 00, 00 ff, ??

**Comment by c3rb3ru5d3d53c** [comment]
Did you check to see if the instructions are also attributed with the `invalid_instructions` value greater than zero?

**Comment by nofiv** [comment]
Ops, I kind of missed that attribute. ?? is incorrect, however 00 00, 00 ff are correct. There are some long sequences of instructions with 00 00 - ~100 of them

**Comment by c3rb3ru5d3d53c** [comment]
Having  a quick look here `capstone` is not signifying to us that these instructions are invalid.

As such this is an issue that should likely be taken upstream to the capstone repo if it is one.

![image](https://user-images.githubusercontent.com/79795199/147838641-cd998427-fc63-4183-8bd6-25def315a0c1.png)

**Comment by c3rb3ru5d3d53c** [comment]
Closing for now :smile:
