### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#37]
Add a CLI parameter to specify a tag string.

Will allow to find similar samples not just across corpus will also allow for tracking threat-actor code reuse

**Comment by rpkrawczyk** [comment]
Opions like `-g malware.emotet` or `-g malware.loader`, etc.

**Comment by rpkrawczyk** [comment]
The Decompiler outputs a json part in Decompiler::GetTrait(), should the tags be added there? This would result in the need of storing the traits in the decompiler.

**Comment by rpkrawczyk** [comment]
In the json we have two possibilities:
 1. "tags" : "alpha,beta,gamma"
 2. "tags" : ["alpha","beta","gamma"]

I would prefer the latter. Which should we chose?

**Comment by rpkrawczyk** [comment]
OK, some heavy cleanup is due to make the tags visible in the json output. This needs to be rechecked.

**Comment by c3rb3ru5d3d53c** [comment]
> In the json we have two possibilities:
> 
> 1. "tags" : "alpha,beta,gamma"
> 2. "tags" : ["alpha","beta","gamma"]
> 
> I would prefer the latter. Which should we chose?

Let's go with a simple list so option 2!
