### ISSUE TITLE
Windows: CMake Parameter Issue

### ISSUE THREAD

**Issue by jbx81-1337** [c3rb3ru5d3d53c/binlex#38]
This parameter "CMAKE_CXX_FLAGS_RELEASE:STRING=" is inside C/C++ compiling options and breaks IntelliSense of VisualStudio, removing it manually fix the problem. trying to understand how to remove it.

**Comment by c3rb3ru5d3d53c** [comment]
This is for the windows build, for GeekWeek we focus on linux build for now :smile:
