### ISSUE TITLE
CIL/.NET Binary Support

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#40]
This is already partially implemented in the branch `pe_cil`.

Work with this branch to add the necessary functionality.

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/166733429-d7f506e0-c494-4199-a307-71ec59f6d7a1.png)

password `infected`
[dcfa2cc5cdbbe0980658219c7dcc22de.zip](https://github.com/c3rb3ru5d3d53c/binlex/files/8622384/dcfa2cc5cdbbe0980658219c7dcc22de.zip)

**Comment by c3rb3ru5d3d53c** [comment]
https://twitter.com/James_inthe_box/status/1521880299575017473

**Comment by jershmagersh** [comment]
> ![image](https://user-images.githubusercontent.com/79795199/166733429-d7f506e0-c494-4199-a307-71ec59f6d7a1.png)
> 
> password `infected` [dcfa2cc5cdbbe0980658219c7dcc22de.zip](https://github.com/c3rb3ru5d3d53c/binlex/files/8622384/dcfa2cc5cdbbe0980658219c7dcc22de.zip)

This is addressed here: https://github.com/c3rb3ru5d3d53c/binlex/pull/98.

**Comment by c3rb3ru5d3d53c** [comment]
Testing this again now :smile:

**Comment by c3rb3ru5d3d53c** [comment]
Closing for now :smile: we can still continue improvements!
