### ISSUE TITLE
Decompiler Core Improvements

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#42]
- Recursive (rework - yes or no)
- Coverage for C++ (vtable)
 - Delphi
 - Rust
 - Go
- VB6 (stop don't run)

**Comment by herrcore** [comment]
## Discovery 
Before attempting to add additional disassembly passes we need to do a bit of discovery and documentation first. Mainly we want to have a documentation that explains exactly what coverage we *expect*, how the basic blocks are separated into a control flow graph (CFG),  and how the wild carding is applied. Changes to either the coverage, the CFG, or the wildcarding will make all future traits generated incompatible with past traits so it is important that these not be changed often, and that they be well documented. 

### General Questions To Answer
- What sections of a file are submitted for disassembly? Does this depend on the execution permissions? 
- How are the basic blocks parsed out for a trait. Are they split into a normalized CFG or is there overlap?
- Should the disassembler be responsible for detecting non-native code or should this be handled elsewhere? How do we determine if this is VB6?
- How is wildcarding applied? 
  - Are all immediates removed or only memory references? 
  - Can an argument be added to control this?

### Coverage
- Under with pure c code what coverage do we expect? Are there any known limitations ? 
- Is it possible to specify new disassembly start points? Possibly extend this to allow for PDB data later?
- What sort of coverage is provided for compiled languages that result in non-referenced functions (ie. vtables)? 
  - Coverage for C++ with inheritance 
  - Coverage for Delphi 
  - Coverage for GO
  - Coverage for Rust

**Comment by c3rb3ru5d3d53c** [comment]
Q: What sections of a file are submitted for disassembly? Does this depend on the execution permissions?
A: Right now only sections marked as executable are extracted and submitted for disassembly.

Q: Should the disassembler be responsible for detecting non-native code or should this be handled elsewhere? How do we determine if this is VB6?
A: To get us further in this geekweek this can be a responsibility delegated to the end user, perhaps we provide a yara signature in the repository for them to use.

Q: How is wildcarding applied? Can an argument be added to control this?
A1: Right now it is applied only to memory references, however I do believe we should also add support for immediates.
A2: Yes, additional code can be added in a specific function to add this functionality, I can point you to it :)

Q: Is it possible to specify new disassembly start points? Possibly extend this to allow for PDB data later?
A1: Yes, the initial disassembly starting points are all based on a C++ queue, this queue is started by the parser for each file format. This is already started for collecting DLL or shared library functions in the code.
A2: It is possible to extend for PDB data later, however I think it maybe out of scope for this GeekWeek

Q: What sort of coverage is provided for compiled languages that result in non-referenced functions (ie. vtables)?
A: Currently we do not have any code that specifically looks for vtables, it could certainly be additional logic that can be added to the initial parsing of the file, which will then populate more offsets with their associated sections to fill the decompile queue.

**Comment by herrcore** [comment]
Basic blocks are not normalized (they overlap):

Simple example: `pe.emotet.x86`

BB at offset 121979 overlaps with BB at offset 120533. We don't need to normalize this but it might be nice to have a flag make it an option as it will be a large performance hit.

**Comment by herrcore** [comment]
Added the pe and elf entry points to the functions to be processes instead of just pushing the address of the start of the function b86a709cb83490064629b8c32b29999f455602ed

Improved coverage for **pe.x86**

Function coverage: **1.24%** ( Missing 476 from total 482 )  ->  Function coverage: **54.98%**  ( Missing 217 from total 482 )
Basic block coverage: **1.68%** ( Missing 2979 from total 3030 ) ->  Basic block coverage: **63.17%**  ( Missing 1116 from total 3030 )

**Comment by c3rb3ru5d3d53c** [comment]
Leaving this one open just changing title to Improvements so we can track

**Comment by c3rb3ru5d3d53c** [comment]
Having a look into this now, hoping to make some improvements to the linear diassembler pass, reading the paper, maybe important to note the most useful reading is in the implementation section :)

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/169724279-23edcecf-65c5-4fd2-bcf6-7dce50bdb82c.png)

```c++
if (IsCallInsn(cs_ins) == true && valid_block_count >= 1){
    CollectInsn(cs_ins, sections, index);
}
```

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/169724513-53a3f5b0-d10d-4baf-92c6-fc2f24411d1c.png)

This one appears to be done and implemented as the method `IsSemanticNopInsn`.

**Comment by c3rb3ru5d3d53c** [comment]
Added the method `IsInvalidNopInsn`, as this was in `nuculeus` because Visual Studio sometimes places semantic nops at the function start and Visual Studio uses int3 for padding. Thus, I added the enum `BINARY_TYPE`. I also changed the places we are using `typedef enum` with the appropriate `enum` as parameters.

```c++
bool Disassembler::IsInvalidNopInsn(cs_insn *insn){
    return IsNopInsn(insn) ||
        (IsSemanticNopInsn(insn) && (file_reference.binary_type != BINARY_TYPE_PE)) ||
        (IsTrapInsn(insn) && (file_reference.binary_type == BINARY_TYPE_PE));
}
```

We still get false positives with this, so I'm continuing to investigate.

**Comment by c3rb3ru5d3d53c** [comment]
Well we are here now:

```text
Function coverage: 50.41%  ( Missing 239 from total 482 )
Basic block coverage: 61.75%  ( Missing 1159 from total 3030 )
Basic block errors: 0
Extra blocks from binlex: 595
```

False positives down a lot now, after removing the extra else statement from `LinearDisassemble`.

**Comment by c3rb3ru5d3d53c** [comment]
![image](https://user-images.githubusercontent.com/79795199/170248833-6ac27d46-6d12-4b79-ade6-d94c50d09c41.png)

I'll start looking at detecting switch jump tables, we can probably add this to the `CollectOperands` method, so instead of doing multiple passes, we should be able to make it part of our continual collection of blocks and functions.

**Comment by jbx81-1337** [comment]
Apply a wildcard of already-known function to others blocks:
After we extract all the "easy" we can generate the epilogue/prologue wildcards of these and apply the wildcards to all the others blocks, if we find a match we can tag a block as "epilogue" or "prologue" and use it to identify other functions.
