### ISSUE TITLE
Cleaning the docker.sh script

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#44]
Using the `blserver` branch, investigate the use of Docker Swarm instead of `docker.sh` to generate the `docker-compose.yml`.

This should make deployment of our containers much more user friendly.

If we decide to go with Docker Swarm let c3rb3ru5 know and begin working at replacing `docker.sh`

**Comment by g0nzu1** [comment]
If a `config` folder is already created in the binlex directory before running the `docker.sh` script, the script will not produce public/private keys with OpenSSL and completely skips that step. 
Initial Hypothesis: OpenSSL function breaks if the directory already exist. 
I will look into fixing this and make sure that everything in the directory gets overwritten should the `docker.sh` script runs again. 

This would support users that may want to change the number of shards, replicas, brokers and router even after they ran the script once.
