### ISSUE TITLE
Entropy uses map to store frequncies, a vector should be used

### ISSUE THREAD

**Issue by rpkrawczyk** [c3rb3ru5d3d53c/binlex#54]
in float Common::Entropy(string trait) a map<char,int> is used to store frequencies. Every access via operator[] is logarithmic in the size of the container which would result in a slower runtime.

**Comment by rpkrawczyk** [comment]
Use vector, remember to skip zero frequency elements.

**Comment by c3rb3ru5d3d53c** [comment]
Fixed, and in milestone branch now thanks to @emgon !
