### ISSUE TITLE
Unit Testing Against IDA Json Output

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#59]

**Comment by herrcore** [comment]
Initial commits: 17e9dcb80cb6bccc57f906bb0c7e279a01627dfe , 2cabcd85527e2945144ac970a85dc9b55962e0e0

We have a repeatable process to pull the data from IDA:
https://gist.github.com/herrcore/ba185787ee4df117e90f1accbf3749dc

Some work still needs o be done here though. Mainly the coverage script is horribly inefficient and won't complete for large files like the Delphi one... one possible solution is to convert these into a hash map so we can just do a direct compare? 

Also we need to have a discussion about the we "want" binlex to parse tricky scenarios (indirect calls, jmp to fn, jmp to imports, etc.) nothing is necessarily bad we just need to document so we can replicate this in the IDA data generation scripts. 

## Current Coverage 

**pe.emotet.x86**
Function coverage: 95.67%  ( Missing 11 from total 254 )
Basic block coverage: 94.73%  ( Missing 97 from total 1841 )
Basic block errors: 0

**pe.trickbot.x86**
Function coverage: 57.14%  ( Missing 3 from total 7 )
Basic block coverage: 52.94%  ( Missing 8 from total 17 )
Basic block errors: 1

**pe.trickbot.x86_64**
Function coverage: 76.95%  ( Missing 80 from total 347 )
Basic block coverage: 79.26%  ( Missing 1149 from total 5541 )
Basic block errors: 0

**pe.delphi.projecthook.x86**
timeout!

**pe.x86**
Function coverage: 1.24%  ( Missing 476 from total 482 ) 
Basic block coverage: 1.68%  ( Missing 2979 from total 3030 ) 
Basic block errors: 0

**pe.x86_64**
Function coverage: 43.79%  ( Missing 190 from total 338 )
Basic block coverage: 42.2%  ( Missing 1968 from total 3405 )
Basic block errors: 22

**elf.x86**
Function coverage: 7.23%  ( Missing 77 from total 83 )
Basic block coverage: 12.67%  ( Missing 441 from total 505 )
Basic block errors: 26

**elf.x86_64**
binlex error!

**Comment by c3rb3ru5d3d53c** [comment]
These tests are working for me ty!

**Comment by herrcore** [comment]
Sped this up a lot! It's fast enough that we can add it to the build script now: 10e4f87ac9b4ff08fcee4cac307755861071db38

**Comment by pisco-sour** [comment]
Something is strange wrt coverage results of the trickbot sample.

**1. Original master branch:**
cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.trickbot.x86.ida.json test_results/trickbot_pe_x86_master.txt 
Function coverage: 0.0%  ( Missing 7 from total 7 )
Basic block coverage: 0.0%  ( Missing 17 from total 17 )
Basic block errors: 0
Extra blocks from binlex: 36

**2. Pure recursive search**
cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.trickbot.x86.ida.json test_results/trickbot_pe_x86_no_linear.txt 
Function coverage: **57.14%**  ( Missing 3 from total 7 )
Basic block coverage: **35.29%**  ( Missing 11 from total 17 )
Basic block errors: 0
Extra blocks from binlex: 0

**3. Recursive with new linear search**
cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.trickbot.x86.ida.json test_results/trickbot_pe_x86_with_linear.txt 
Function coverage: **57.14%**  ( Missing 3 from total 7 )
Basic block coverage: **35.29%**  ( Missing 11 from total 17 )
Basic block errors: 0
Extra blocks from binlex: 67

**Comment by pisco-sour** [comment]
**1. Original master branch**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.delphi.projecthook.x86.ida.json test_results/**delphi_pe_x86_master.txt**
Function coverage: **2.62%**  ( Missing 13143 from total 13496 )
Basic block coverage: **2.85%**  ( Missing 77250 from total 79520 )
Basic block errors: 2269
Extra blocks from binlex: **51802**

**2. Pure recursive search**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.delphi.projecthook.x86.ida.json test_results/**delphi_pe_x86_no_linear.txt**
Function coverage: **3.12%**  ( Missing 13075 from total 13496 )
Basic block coverage: **4.33%**  ( Missing 76075 from total 79520 )
Basic block errors: 12
Extra blocks from binlex: **635**

**3. Recursive with new linear search**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.delphi.projecthook.x86.ida.json test_results/**delphi_pe_x86_with_linear.txt**
Function coverage: **25.26%**  ( Missing 10087 from total 13496 )
Basic block coverage: **39.61%**  ( Missing 48025 from total 79520 )
Basic block errors: 27
Extra blocks from binlex: **51730**

**Comment by pisco-sour** [comment]
### Emotet sample

**1. Original master branch**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.emotet.x86.ida.json test_results/**emotet_pe_x86_master.txt** 
Function coverage: **0.39%**  ( Missing 253 from total 254 )
Basic block coverage: **1.09%**  ( Missing 1821 from total 1841 )
Basic block errors: 20
Extra blocks from binlex: **1853**

**2. Pure recursive search**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.emotet.x86.ida.json test_results/**emotet_pe_x86_no_linear.txt** 
Function coverage: **96.85%**  ( Missing 8 from total 254 )
Basic block coverage: **96.09%**  ( Missing 72 from total 1841 )
Basic block errors: 0
Extra blocks from binlex: **123**

**3. Recursive with new linear search**

cvisinescu@ubuntu ~/p/G/b/binlex (disassembler-optimization)> python ./tests/coverage.py ./tests/ida_baseline/pe.emotet.x86.ida.json test_results/**emotet_pe_x86_with_linear.txt**
Function coverage: **96.85%**  ( Missing 8 from total 254 )
Basic block coverage: **96.09%**  ( Missing 72 from total 1841 )
Basic block errors: 0
Extra blocks from binlex: **573**

**Comment by c3rb3ru5d3d53c** [comment]
Closing for now :smile:
