### ISSUE TITLE
Dedupe Traits

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [c3rb3ru5d3d53c/binlex#60]
Fix trait duplication

**Comment by c3rb3ru5d3d53c** [comment]
https://github.com/c3rb3ru5d3d53c/binlex/blob/0f847575eb53ccc158ce33dfc9480a6caf61e2b0/src/decompiler.cpp#L518-L527

Looks like no check if addr is visited here, maybe why we getting dupes

**Comment by jbx81-1337** [comment]
This check seems dont fix the issue, trying to put a 'guard' check after the element is get from the queue by the DecompilerWorker and check if is visited (this should not be visited) if we dont have an issue on address scheduling this bug is on TraitWorker

**Comment by c3rb3ru5d3d53c** [comment]
@jbx81-1337 you may want to try checking out the branch `staging` as we keep all our bleeding edge changes there to see if there is any difference.

**Comment by c3rb3ru5d3d53c** [comment]
@herrcore did we address this, this issue ongoing?

**Comment by c3rb3ru5d3d53c** [comment]
https://github.com/c3rb3ru5d3d53c/binlex/blob/dd107c1d725849ef10c5b318a6383e4a00f60b81/src/decompiler.cpp#L229-L257

**Comment by jbx81-1337** [comment]
Seems AppendTrait is called multiple times for the same trait, i dont understand if is possible to trigger multiple conditional path in the section code provided by @c3rb3ru5d3d53c . I have tried to switch from 'if' to 'else if' but seems equal, my suggestion is to keep track of processed trait with AppendTrait in 'visited' map, set address as DECOMPILER_VISITED_APPENDED and remove the duplicated trait.

**Comment by c3rb3ru5d3d53c** [comment]
Investigating this one now :smile:

**Comment by c3rb3ru5d3d53c** [comment]
> Seems AppendTrait is called multiple times for the same trait, i dont understand if is possible to trigger multiple conditional path in the section code provided by @c3rb3ru5d3d53c . I have tried to switch from 'if' to 'else if' but seems equal, my suggestion is to keep track of processed trait with AppendTrait in 'visited' map, set address as DECOMPILER_VISITED_APPENDED and remove the duplicated trait.

So I thought about this a decent amount, there are times where a jump instruction can be referenced, and I also notice that functions are not duplicated. As such, I think that this issue does stem from what you are saying. Now the hard part is to determine where to best implement code to solve that. We could implement an additional check perhaps to the method `CollectOperands` under each switch case perhaps by checking `sections[index].addresses` and their associated types. I think this would be much more ideal than adding it to the method `AppendTrait` as I think this would be inefficient.

**Comment by c3rb3ru5d3d53c** [comment]
So believe I found the issue, we need to split `sections[index].addresses` into two sets, this would be easier to maintain, I could be incorrect, however it would appear we cannot store 2 different values for the same key in a map. This is needed because Functions will start with a block at the same address.

![image](https://user-images.githubusercontent.com/79795199/169428638-ef405b13-472a-4650-b0db-99baf7680d7d.png)

**Comment by jbx81-1337** [comment]
Ok, I don't really understand where the issue is because I noticed that the duplicated traits  are type=block, and in any case the actual code doesn't push the addr on the Worker queue if Is already visited, I also made some checks for older version of binlex and seems has the same bug
