### ISSUE TITLE
docker.sh write/overwrite openssl certs and artifacts if `config` folder already exist

### ISSUE THREAD

**Issue by g0nzu1** [c3rb3ru5d3d53c/binlex#62]
The docker script will not execute the OpenSSL code if a `config` folder already exist in the binlex directory. Preventing user from updating/changing the configuration of `shards`, `routers`, `broker` and `replicas` after the script has run once.

**Comment by g0nzu1** [comment]
Line 384 - 386 if what generates this behaviour

**Comment by c3rb3ru5d3d53c** [comment]
We can remove the logic for that if you wish :)
